services:
  postgres:
    image: postgres:16
    container_name: sneaker-store-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sneaker_store
      POSTGRES_USER: sneaker_app
      POSTGRES_PASSWORD: sneaker_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
